// sample/solid/components/organisms/MarketSurface.tsx
import { Index } from "solid-js";
import type { MarketRow, SurfaceMode } from "../../types.js";
import { CardRow } from "./CardRow.js";
import { EditorRow } from "./EditorRow.js";
import { TableRow } from "./TableRow.js";

interface MarketSurfaceProps {
  readonly onHoverRow?: (rowId: number) => void;
  readonly rows: readonly MarketRow[];
  readonly surfaceMode: SurfaceMode;
}

function CardSurface(props: Pick<MarketSurfaceProps, "rows">): JSX.Element {
  return (
    <div class="market-grid">
      <Index each={props.rows}>{(row) => <CardRow row={row} />}</Index>
    </div>
  );
}

function EditorSurface(props: Pick<MarketSurfaceProps, "rows">): JSX.Element {
  return (
    <div class="editor-grid">
      <Index each={props.rows}>{(row) => <EditorRow row={row} />}</Index>
    </div>
  );
}

function TableSurface(
  props: Pick<MarketSurfaceProps, "onHoverRow" | "rows">,
): JSX.Element {
  return (
    <div class="order-book">
      <div class="order-book__header">
        <div class="column-symbol">Symbol</div>
        <div class="column-venue">Venue</div>
        <div class="column-price">Price</div>
        <div class="column-change">Change</div>
        <div class="column-volume">Volume</div>
        <div class="column-trades">Trades</div>
        <div class="column-heat">Heat</div>
      </div>
      <div class="order-book__body">
        <Index each={props.rows}>
          {(row) => <TableRow row={row} onHoverRow={props.onHoverRow} />}
        </Index>
      </div>
    </div>
  );
}

export function MarketSurface(props: MarketSurfaceProps): JSX.Element {
  if (props.surfaceMode === "cards") {
    return <CardSurface rows={props.rows} />;
  }

  if (props.surfaceMode === "editor") {
    return <EditorSurface rows={props.rows} />;
  }

  return <TableSurface rows={props.rows} onHoverRow={props.onHoverRow} />;
}

// sample/react/components/organisms/MarketSurface.tsx
import { memo, type JSX } from "react";
import type { MarketStore, SurfaceMode } from "../../types.js";
import { CardRow } from "./CardRow.js";
import { EditorRow } from "./EditorRow.js";
import { TableRow } from "./TableRow.js";

interface MarketSurfaceProps {
  readonly onHoverRow?: (rowId: number) => void;
  readonly store: MarketStore;
  readonly rowIds: readonly number[];
  readonly surfaceMode: SurfaceMode;
}

const CardSurface = memo(function CardSurface(
  props: Pick<MarketSurfaceProps, "onHoverRow" | "store" | "rowIds">,
): JSX.Element {
  return (
    <div className="market-grid">
      {props.rowIds.map((rowId) => (
        <CardRow
          key={rowId}
          store={props.store}
          rowId={rowId}
          onHoverRow={props.onHoverRow}
        />
      ))}
    </div>
  );
});

const EditorSurface = memo(function EditorSurface(
  props: Pick<MarketSurfaceProps, "onHoverRow" | "store" | "rowIds">,
): JSX.Element {
  return (
    <div className="editor-grid">
      {props.rowIds.map((rowId) => (
        <EditorRow
          key={rowId}
          store={props.store}
          rowId={rowId}
          onHoverRow={props.onHoverRow}
        />
      ))}
    </div>
  );
});

const TableSurface = memo(function TableSurface(
  props: Pick<MarketSurfaceProps, "onHoverRow" | "store" | "rowIds">,
): JSX.Element {
  return (
    <div className="order-book">
      <div className="order-book__header">
        <div className="column-symbol">Symbol</div>
        <div className="column-venue">Venue</div>
        <div className="column-price">Price</div>
        <div className="column-change">Change</div>
        <div className="column-volume">Volume</div>
        <div className="column-trades">Trades</div>
        <div className="column-heat">Heat</div>
      </div>
      <div className="order-book__body">
        {props.rowIds.map((rowId) => (
          <TableRow
            key={rowId}
            store={props.store}
            rowId={rowId}
            onHoverRow={props.onHoverRow}
          />
        ))}
      </div>
    </div>
  );
});

export const MarketSurface = memo(function MarketSurface(
  props: MarketSurfaceProps,
): JSX.Element {
  if (props.surfaceMode === "cards") {
    return (
      <CardSurface
        store={props.store}
        rowIds={props.rowIds}
        onHoverRow={props.onHoverRow}
      />
    );
  }

  if (props.surfaceMode === "editor") {
    return (
      <EditorSurface
        store={props.store}
        rowIds={props.rowIds}
        onHoverRow={props.onHoverRow}
      />
    );
  }

  return (
    <TableSurface
      store={props.store}
      rowIds={props.rowIds}
      onHoverRow={props.onHoverRow}
    />
  );
});
